<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Action extends Model
{
    protected $table = "actions";

    protected $fillable = ['payload_id', 'actor_id', 'name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     *
     * Получение объекта по id
     */
    public function actor() {
        return $this->belongsTo('App\Models\Actors', 'actor_id', 'id');
    }

    /**
     * @return array
     *
     * Кастомизация вывода
     */
    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        unset($data['created_at']);
        unset($data['updated_at']);
        unset($data['payload_id']);
        if ($this->newQuery()->where('actor_id', '=', $data['actor_id'])->first()->id == $data['id']) {
            $data['actor'] = $this->actor()->first()->name;
        }
        $data['action'] = $data['name'];
        unset($data['id']);
        unset($data['actor_id']);
        unset($data['name']);
        return $data;
    }
}
