<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Crypt;

class Document extends Model
{
    const STATUS_DRAFT = 'draft';

    protected $table = "documents";

    protected $fillable = ['status', 'payload_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     *
     * Получение объекта payload по id
     */
    public function payload() {
        return $this->belongsTo('App\Models\Payload', 'payload_id', 'id');
    }

    /**
     * @return array
     *
     * Кастомизация вывода
     */
    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        unset($data['payload_id']);
        $data['id'] = Crypt::encrypt($data['id']);
        $content = $this->payload()->first();
        $data['payload'] = $content ? $content : null;
        return
            ['document' =>
                [
                    'id'      => (string)$data['id'],
                    'status'   => (string)$data['status'],
                    'payload'    => (object)$data['payload'],
                    'created_at' => $data['created_at'],
                    'updated_at' => $data['updated_at'],
                ]
            ];
    }

}
