<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Meta extends Model
{
    protected $table = 'meta';

    protected $fillable = ['type', 'color'];

    /**
     * @return array
     *
     * Кастомизация вывода
     */
    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        unset($data['id']);
        if ($data['color'] == null) {
            unset($data['color']);
        }
        unset($data['created_at']);
        unset($data['updated_at']);
        return $data;
    }
}
