<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payload extends Model
{
    protected $table = "payloads";

    protected $fillable = ['actor', 'meta_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     *
     * Получение объекта "Мета" по id
     */
    public function meta() {
        return $this->belongsTo('App\Models\Meta', 'meta_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     *
     * Получение объекта "Action" по id
     */
    public function actions() {
        return $this->hasMany('App\Models\Action');
    }

    /**
     * @return array
     *
     * Кастомизация вывода
     */
    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        unset($data['meta_id']);
        unset($data['id']);
        unset($data['created_at']);
        unset($data['updated_at']);
        $data['meta'] = $this->meta()->first();
        $data['actions'] = $this->actions()->get();
        return $data;
    }
}
